### ISSUE TITLE
Using a custom URL

### ISSUE THREAD

**Issue by CrowdHailer** [codedge-llc/kadabra#14]
Are their any tests that actually check what is sent over a connection?

This lead me to my second question. Is there anyway to use a custom url so that you can send push requests to a localhost version and check it works.

**Comment by hpopp** [comment]
The tests were written specifically to check for responses from the Go community's test server, so it wouldn't make a lot of sense to swap out the url. That said, I'm not opposed to additional tests that check a local server.

**Comment by CrowdHailer** [comment]
My apologies I think I meant for this to be a question on pidgeon.
