### ISSUE TITLE
Only one connection supported per host

### ISSUE THREAD

**Issue by fertel** [codedge-llc/kadabra#15]
The wrong stream id could feasibly be loaded from the registry as they are tied to host instead of to the specific calling process/connection

**Comment by hpopp** [comment]
Thanks for the catch. I'll revisit this when I properly address stream supervision. All of the rework for `v0.3` isn't by any means final yet.

**Comment by fertel** [comment]
A few other issues I noticed can add them if you'd like - for example you are leaking stream processes when they close. I am forking it to remove dependencies on all the other processes - i.e. each connection can handle multiple streams but relies on only one process per connection - fits my use case as we are dealing with large per machine load and speedy response time requirements.

Thanks for your work. By far most performant http2 lib as it stands, haven't dug too much into chatterbox to figure out what makes it so slow i.e. each call has like 20+ ms of overhead

**Comment by hpopp** [comment]
Fixed both the process leak and single connection issues. Connections are now keyed by a `ref` in the registry. 

To be fixed: streams can be orphaned in the registry if the connection crashes.
