### ISSUE TITLE
Memory leak in Kadabra.Supervisor

### ISSUE THREAD

**Issue by talklittle** [codedge-llc/kadabra#20]
My application using Pigeon 1.1.0 and Kadabra 0.3.2 crashed (after 28 days uptime) with:

    eheap_alloc: Cannot allocate 762886488 bytes of memory (of type "heap")

Running the `erl_crash.dump` through:

    /usr/lib/erlang/lib/observer-2.5/priv/bin/cdv erl_crash.dump

Shows `Elixir.Kadabra.Supervisor` using 721 MB of memory at the time of crash. Which is 90x the next-biggest process, `ssl_manager` at 8 MB.

**Comment by hpopp** [comment]
I'll take a look, probably old connections aren't getting cleaned up.

**Comment by hpopp** [comment]
Looks like the hpack tables survive connection close. Fixed with #21, though I want to do some rework before publish.

**Comment by talklittle** [comment]
@hpopp Wow, thanks for such a quick fix!
